### ISSUE TITLE
Error: ENOENT: no such file or directory, stat

### ISSUE THREAD

**Issue by frenchy64** [turtlequeue/setup-babashka#12]
https://github.com/frenchy64/dependabot-lein-via-mvn/runs/5589311551?check_suite_focus=true#step:6:9

```
Run turtlequeue/setup-babashka@v1
  with:
    babashka-version: 0.7.8
  env:
    ACTION_CACHE_VERSION: v1
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.14-1/x64
    LEIN_HOME: /opt/hostedtoolcache/Leiningen/[2](https://github.com/frenchy64/dependabot-lein-via-mvn/runs/5589311551?check_suite_focus=true#step:6:2).9.8/x64
Versions of babashka available: 
Error: ENOENT: no such file or directory, stat
/usr/bin/bash /home/runner/work/_temp/96e5da7d-bfe9-405d-9656-25841926e674 --install-dir 
Installs latest (or specific) version of babashka. Installation directory defaults to /usr/local/bin.

Usage:
install [--dir <dir>] [--download-dir <download-dir>] [--version <version>] [--checksum <checksum>] [--static]

Defaults:
 * Installation directory: /usr/local/bin
 * Download directory: temporary
 * Checksum: no
 * Static binary: false
 * Version: <Latest release on github>
(node:1601) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/bash' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/turtlequeue/setup-babashka/v1/dist/index.js:1026:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/turtlequeue/setup-babashka/v1/dist/index.js:1009:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/turtlequeue/setup-babashka/v1/dist/index.js:90[3](https://github.com/frenchy64/dependabot-lein-via-mvn/runs/5589311551?check_suite_focus=true#step:6:3):27)
    at ChildProcess.emit (events.js:31[4](https://github.com/frenchy64/dependabot-lein-via-mvn/runs/5589311551?check_suite_focus=true#step:6:4):20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:67[5](https://github.com/frenchy64/dependabot-lein-via-mvn/runs/5589311551?check_suite_focus=true#step:6:5):12)
(node:1[6](https://github.com/frenchy64/dependabot-lein-via-mvn/runs/5589311551?check_suite_focus=true#step:6:6)01) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1601) [DEP001[8](https://github.com/frenchy64/dependabot-lein-via-mvn/runs/5589311551?check_suite_focus=true#step:6:8)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by piranha** [comment]
Hit the same problem: it's because `v1` is not pointing at the last release of major version 1, but rather an old commit. Using `v1.7.0` fixes that issue.
